spring:
  application:
    name: poupai-backend
  data:
    mongodb:
      uri: ${MONGODB_URI}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  address: 0.0.0.0


app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000

r2:
  endpoint: https://cd9bb7c9721c176571ba40bebc1792d8.r2.cloudflarestorage.com
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  bucket: poupai-uploads
  presigned-expiry-minutes: 60