spring:
  application:
    name: poupai-backend
  data:
    mongodb:
      uri: mongodb+srv://wtcadmin:20605280@wtc.khkq5ro.mongodb.net/poupaidb?retryWrites=true&w=majority&appName=poupai
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  address: 0.0.0.0


app:
  jwt:
    secret: poupai_secret_key_minimo_256_bits_seguro_aqui
    expiration-ms: 86400000

r2:
  endpoint: https://cd9bb7c9721c176571ba40bebc1792d8.r2.cloudflarestorage.com
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  bucket: poupai-uploads
  presigned-expiry-minutes: 60